### ISSUE TITLE
Explain how this crate is different from language-tags

### ISSUE THREAD

**Issue by zbraniecki** [mike-engel/accept-language-rs#4]
How is this crate different from https://github.com/pyfisch/rust-language-tags - it would be useful to understand where those two differ in goals or implementation.

**Comment by mike-engel** [comment]
@zbraniecki The goals are different. This crate is at a higher level in order to conform to the accept-language header on the web. That means that this crate can parse the quality modifications and order an array of users languages rather than a single tag at a time. Thus, this crate can parse the following where the language-tags crate could not:

```rs
"en-US, de;q=0.1, jp;q=0.7" // ["en-US", "jp", "de"]
```

What I should do is us the language-tags crate to achieve the goal of this crate.

Hope this helps, thanks!
